// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var App, Film, Item, Page, Page_Login, Page_Main, Page_Person, Page_Register, Person, User, check_app_is_init, conf, error,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = void 0;

  conf = {
    no_poster_url: "img/noposter.jpg",
    filter_delay: 1000,
    api_url: 'api/v1/',
    tpl_prefix: 'jade/_part_'
  };

  error = function(txt, type) {
    if (type == null) {
      type = "norm";
    }
    if (type === "crit") {
      throw new Error("CRITICAL ERROR: " + txt);
    } else {
      return console.log("ERROR: " + txt);
    }
  };

  check_app_is_init = function(c) {
    if (!window.App) {
      return error("App is not init", "crit");
    } else {
      return c._app = window.App;
    }
  };

  Page = (function() {
    function Page() {
      check_app_is_init(this);
      this._e = {};
      this._visible = false;
    }

    Page.prototype.show = function() {
      return this._visible = true;
    };

    Page.prototype.hide = function() {
      return this._visible = false;
    };

    Page.prototype.isVisible = function() {
      return this._visible;
    };

    return Page;

  })();

  Item = (function() {
    function Item(opts, callback) {
      if (opts == null) {
        opts = {};
      }
      if (callback == null) {
        callback = void 0;
      }
      check_app_is_init(this);
      if (!this._name) {
        error("It's wrong to use parent class", "crit");
      }
      if (opts.place === void 0) {
        this._place = $('<span class="preload_' + this._name + '"></span>');
        if (opts.parent) {
          this._place.appendTo(opts.parent);
        }
        this._app.get_tpl(this._name, (function(_this) {
          return function(tpl_obj) {
            var old_place;
            if (tpl_obj) {
              old_place = _this._place;
              _this._place = tpl_obj.clone();
              if (opts.vals) {
                _this.set_vals(opts.vals);
              }
              _this._place.insertAfter(old_place);
              old_place.remove();
              if (callback) {
                return callback(_this);
              }
            } else {
              return error('Unable to load template for object "' + _this._name + '"');
            }
          };
        })(this));
      } else {
        this._place = opts.place;
        if (opts.vals) {
          this.set_vals(opts.vals);
        }
        if (callback) {
          callback(this);
        }
      }
    }

    Item.prototype.place = function() {
      return this._place;
    };

    Item.prototype.vals = function(name) {
      if (name) {
        return this._vals[name];
      } else {
        return this._vals;
      }
    };

    Item.prototype.set_vals = function(vals) {
      var k, v, _results;
      $.extend(this.reset(), vals);
      if (vals._do_not_set === void 0) {
        _results = [];
        for (k in vals) {
          v = vals[k];
          _results.push($("." + this._name + "-" + k, this._place).html(v));
        }
        return _results;
      }
    };

    Item.prototype.user_is_auth = function() {
      return true;
    };

    Item.prototype.reset = function() {
      return this._vals = {};
    };

    Item.prototype.show = function() {
      return this._place.show();
    };

    Item.prototype.hide = function() {
      return this._place.hide();
    };

    Item.prototype.remove = function() {
      return this._place.remove();
    };

    return Item;

  })();

  Film = (function(_super) {
    __extends(Film, _super);

    function Film(opts, callback) {
      var loc, loc_free, loc_min_price, _i, _len, _ref;
      if (opts == null) {
        opts = {};
      }
      this._name = "afilm";
      if (opts.vals === void 0) {
        opts.vals = {};
      }
      if (opts && opts.place) {
        opts.vals._do_not_set = true;
        opts.vals.id = opts.place.attr("id").substr(4);
        opts.vals.poster = $(".afilm-poster", opts.place).attr("src");
        opts.vals.name = $(".afilm-name", opts.place).text();
        opts.vals.year = $(".afilm-year", opts.place).text();
        opts.vals.watchtext = $(".afilm-watchtext", opts.place).text();
        opts.vals.rating = $(".afilm-rating", opts.place).text();
        opts.vals.relation = {
          rating: $(".rateit", opts.place).rateit("value")
        };
      }
      if (opts.vals.ratings && opts.vals.ratings.cons) {
        opts.vals.rating = opts.vals.ratings.cons;
      }
      if (opts.vals.release_date) {
        opts.vals.year = opts.vals.release_date.substr(0, 4);
      }
      if (opts.vals.locations) {
        loc_free = false;
        loc_min_price = null;
        _ref = opts.vals.locations;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          loc = _ref[_i];
          if (loc.price_type === "f") {
            loc_free = true;
          } else {
            if (loc.price && (loc_min_price === null || loc_min_price > loc.price)) {
              loc_min_price = loc.price;
            }
          }
        }
        opts.vals.watchtext = "";
        if (loc_free) {
          opts.vals.watchtext = "бесплатно";
          if (loc_min_price) {
            opts.vals.watchtext += "<span> или</span><br/>";
          }
        }
        if (loc_min_price) {
          opts.vals.watchtext += "от " + loc_min_price + "р. без рекламы";
        }
      } else {
        delete opts.vals.watchtext;
      }
      Film.__super__.constructor.call(this, opts, (function(_this) {
        return function() {
          var rFloor, rInt, rel, ri;
          if (!opts.place) {
            $(".rateit", _this._place).rateit();
          }
          ri = $(".rateit", _this._place);
          ri.rateit("min", 0).rateit("max", 10).bind("beforerated beforereset", function(event) {
            if (!_this.user_is_auth()) {
              alert("You have to be signed");
              return event.preventDefault();
            }
          }).bind("reset rated", function(event) {
            return _this.action_rate(ri.rateit("value"));
          });
          rel = _this.vals("relation");
          if (rel) {
            if (rel.rating !== void 0) {
              rInt = Math.floor(rel.rating);
              rFloor = 0;
              if (rel.rating - rInt > 0.5) {
                rFloor = 0.5;
              }
              ri.rateit("value", rInt + rFloor);
            }
          }
          $(".afilm-tolist", _this._place).click(function() {
            return _this.action_toggle_subscribe();
          });
          if (callback) {
            return callback(_this);
          }
        };
      })(this));
    }

    Film.prototype.action_toggle_subscribe = function(status) {
      var action, new_subscribed, rel;
      if (this.user_is_auth()) {
        rel = this.vals("relation");
        if (status !== void 0) {
          new_subscribed = status;
        } else {
          new_subscribed = true;
          if (rel && rel.subscribed) {
            new_subscribed = false;
          }
        }
        if (new_subscribed) {
          action = "update";
        } else {
          action = "destroy";
        }
        return this._app.rest.films.action.subscribe[action](this.vals("id")).done(function() {
          return rel.subscribed = new_subscribed;
        });
      }
    };

    Film.prototype.action_rate = function(val) {
      if (this.user_is_auth()) {
        return this._app.rest.films.action.rate.update(this.vals("id"), {
          rating: val
        });
      }
    };

    Film.prototype.reset = function() {
      return this._vals = {
        id: null,
        name: null,
        poster: null,
        year: null,
        rating: null,
        user: null,
        watchtext: null
      };
    };

    Film.prototype.set_vals = function() {
      Film.__super__.set_vals.apply(this, arguments);
      this._place.attr("id", "film" + this._vals.id);
      $(".afilm-name", this._place).attr("href", "/films/" + this._vals.id);
      $(".afilm-poster", this._place).attr("src", this._vals.poster || conf.no_poster_url);
      if (this._vals.rating) {
        $(".afilm-rating", this._place).visible();
      } else {
        $(".afilm-rating", this._place).invisible();
      }
      if (this._vals.watchtext) {
        return $(".afilm-watchtext-place", this._place).visible();
      } else {
        return $(".afilm-watchtext-place", this._place).invisible();
      }
    };

    return Film;

  })(Item);

  Person = (function() {
    function Person(parent) {
      this.parent = parent;
      checkAppIsInit(this);
    }

    return Person;

  })();

  User = (function() {
    function User(parent) {
      this.parent = parent;
      checkAppIsInit(this);
    }

    return User;

  })();

  App = (function() {
    var _active_page, _options, _pages, _query_params, _templates, _user;

    _options = {
      api_url: 'api/v1/',
      tpl_prefix: 'jade/_part_'
    };

    _user = {
      id: null,
      name: ""
    };

    _templates = {};

    _pages = {};

    _active_page = void 0;

    _query_params = void 0;

    App.prototype.opts = function(name) {
      if (name) {
        return this._options[name];
      } else {
        return this._options;
      }
    };

    function App(opts, name) {
      if (opts == null) {
        opts = {};
      }
      if (window.App) {
        error("App is already running", "crit");
      }
      window.App = this;
      if (!$.RestClient) {
        error("No Rest Library found");
      }
      $.extend(_options, opts);
      this.rest = new $.RestClient(conf.api_url);
      this.rest.add("user");
      this.rest.add("users");
      this.rest.add("films");
      this.rest.films.add("action", {
        isSingle: true
      });
      this.rest.films.action.add("rate");
      this.rest.films.action.add("subscribe");
      this.rest.films.action.add("notwatch");
      this.rest.add("persons");
      this.rest.persons.add("filmography", {
        isSingle: true
      });
      this._e = {};
      this._e.search = {
        form: $("#frm_search").submit(function() {
          return false;
        }),
        input: $("#inp_search").keydown((function(_this) {
          return function() {
            return _this.search_keydown;
          };
        })(this)),
        button: $("#inp_button").click((function(_this) {
          return function() {
            _this.search_submit();
            return false;
          };
        })(this))
      };
      this._e.user_reg = {
        place: $("#usr_reg_place")
      };
      this._e.user_guest = {
        place: $("#usr_guest_place")
      };
      this._e.search.input.val(this.query_params("text") || "");
      if (name !== void 0) {
        this.show_page(name, opts.page_conf);
      }
    }

    App.prototype.search_keydown = function(event) {
      if (event.which === 13) {
        this._e.search.button.click();
        return;
      }
      if (event.which === 27) {
        return this._e.input.val("").focus();
      }
    };

    App.prototype.search_submit = function() {
      var text;

      text = this._e.search.input.val() || "";

      if (_active_page === "Main") {

        var a= this.page().filter_changed(text);

          return a;
      } else {
        if (text) {

          text = "?text=" + text;
        }
        return window.location.href = "/" + text;
      }
    };

    App.prototype.query_params = function(name) {
      if (!_query_params) {
        _query_params = $.parseParams();
      }
      if (name) {
        return _query_params[name];
      } else {
        return _query_params;
      }
    };

    App.prototype.get_tpl = function(name, callback) {
      var ajax_opts;
      if (_templates[name]) {
        if (callback) {
          return callback(_templates[name]);
        }
      } else {
        ajax_opts = {
          url: conf.tpl_prefix + name + ".html",
          dataType: "html",
          error: function() {
            error("Unable to load template name \"" + name + "\"");
            if (callback) {
              return callback(void 0);
            }
          },
          success: (function(_this) {
            return function(data) {
              if (callback) {
                return callback(_templates[name] = $(data));
              }
            };
          })(this)
        };
        return $.ajax(ajax_opts);
      }
    };

    App.prototype.register_tpl = function(name, jObj) {
      return _templates[name] = jObj;
    };

    App.prototype.hide_page = function(name) {
      if (!_pages[name]) {
        if (_active_page === name) {
          _pages[name].hide();
          return _active_page = void 0;
        } else {
          return error("Page " + name + " is not active");
        }
      } else {
        return error("No page " + name + "found");
      }
    };

    App.prototype.show_page = function(name, conf) {
      var p;
      p = this.page(name, conf);
      if (p) {
        _active_page = name;
        return p.show();
      } else {
        return error("No page " + name + "found");
      }
    };

    App.prototype.active_page = function() {
      return _active_page;
    };

    App.prototype.page = function(name, conf) {
      var page_obj;
      if (name === void 0) {
        name = _active_page;
      }
      if (_pages[name]) {
        return _pages[name];
      }
      page_obj = new (eval("Page_" + name))(conf);
      return _pages[name] = page_obj;
    };

    return App;

  })();

  Page_Main = (function(_super) {
    var _current_page, _films, _filter_counter, _filter_params, _load_counter;

    __extends(Page_Main, _super);

    _films = [];

    _current_page = 0;

    _load_counter = 0;

    _filter_counter = 0;

    _filter_params = {};

    function Page_Main() {
      var el, filter_name, filter_obj, key, param_name, param_value, params, _ref, _ref1;
      Page_Main.__super__.constructor.apply(this, arguments);
      this._e.output_place = $("#output_place");
      this._e.filter = {
        genre: $("#fil_genre"),
        year_old: $("#fil_year_old"),
        rating: $("#fil_rating"),
        price: $("#fil_price")
      };
      _ref = this._e.filter;
      for (key in _ref) {
        el = _ref[key];
        el.change(((function(_this) {
          return function() {
            return _this.filter_changed_event();
          };
        })(this)));
      }
      this._e.loadmore = {
        place: $("#load-more-place"),
        btn: $("#btn_loadmore").click((function(_this) {
          return function() {
            return _this.load_more();
          };
        })(this))
      };
      this._app.get_tpl("afilm");
      params = this._app.query_params();
      if (params) {
        if (params.q) {
          _filter_params.text = params.q;
        }
        for (param_name in params) {
          param_value = params[param_name];
          _ref1 = this._e.filter;
          for (filter_name in _ref1) {
            filter_obj = _ref1[filter_name];
            if (filter_name === param_name) {
              $("option", filter_obj).each(function() {
                var e;
                e = $(this);
                return e.prop("selected", e.val() === param_value);
              });
            }
          }
        }
      }
      this.update_filter_params();
      $(".afilm-place", this._e.output_place).each(function() {
        return _films.push(new Film({
          place: $(this)
        }));
      });
      if (_films.length < 12) {
        this.load_more();
      }
    }

    Page_Main.prototype.filter_changed_event = function() {
      return this.filter_changed();
    };

    Page_Main.prototype.filter_changed = function(text) {
      var current_filter_counter;
      _filter_counter++;
      if (text) {

        _filter_params.text = text || "";
      }
      current_filter_counter = _filter_counter;
      return setTimeout((function(_this) {
        return function() {
          var opts;
          if (_filter_counter === current_filter_counter) {
            _this.update_filter_params();
            opts = {
              clear_output: true,
              page_loading: false,
              params: _filter_params
            };
            return _this.load_films(opts);
          }
        };
      })(this), conf.filter_delay);
    };

    Page_Main.prototype.load_more = function(page_cnt) {
      var opts;
      if (page_cnt == null) {
        page_cnt = 1;
      }
      this._e.loadmore.btn.prop('disabled', true);
      opts = {
        clear_output: false,
        page_loading: true,
        params: _filter_params
      };
      return this.load_films(opts);
    };

    Page_Main.prototype.update_filter_params = function(update_href) {
      var el, key, query_string, val, _ref;
      if (update_href == null) {
        update_href = true;
      }
      if (_filter_params.text) {
        query_string = "text=" + encodeURI(_filter_params.text);
      } else {
        query_string = "";
      }
      if (_current_page) {
        _filter_params.page = _current_page;
        if (query_string) {
          query_string += "&";
        }
        query_string += "page=" + _current_page;
      }
      _ref = this._e.filter;
      for (key in _ref) {
        el = _ref[key];
        val = el.val();
        if (val && val !== "0") {
          _filter_params[key] = val;
          if (query_string) {
            query_string += "&";
          }
          query_string += key + "=" + val;
        }
      }
      if (query_string) {
        query_string = "?" + query_string;
      }
      if (update_href) {
        if (history && history.pushState) {
          return history.pushState(null, null, query_string);
        }
      }
    };

    Page_Main.prototype.load_films = function(opts) {
      var current_counter, i;
      if (opts == null) {
        opts = {};
      }
      _load_counter++;
      current_counter = _load_counter;
      if (opts.clear_output) {
        i = 0;
        while (i < _films.length) {
          delete _films[i];
          i++;
        }
        _films = [];
        this._e.output_place.empty();
      }
      if (!opts.page_loading) {
        this._e.loadmore.place.hide();
      }
      if (!opts.params) {
        opts.params = {};
      }

      return this._app.rest.films.read("search", opts.params).done((function(_this) {
        return function(data) {
          var item, _i, _len, _ref;
          if (current_counter !== _load_counter) {
            return;
          }
          if (data.items) {
            _ref = data.items;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              item = _ref[_i];
              _films.push(new Film({
                parent: _this._e.output_place,
                vals: item
              }));
            }
          }
          if (Math.ceil(data.total_cnt / data.per_page) > data.page) {
            _this._e.loadmore.place.show();
            _this._e.loadmore.btn.prop('disabled', false);
          }
          _current_page = data.page;
          if (opts.callback) {
            return opts.callback();
          }
        };
      })(this)).fail((function(_this) {
        return function(data) {};
      })(this));
    };

    return Page_Main;

  })(Page);

  Page_Login = (function(_super) {
    __extends(Page_Login, _super);

    function Page_Login() {
      return Page_Login.__super__.constructor.apply(this, arguments);
    }

    return Page_Login;

  })(Page);

  Page_Register = (function(_super) {
    __extends(Page_Register, _super);

    function Page_Register() {
      return Page_Register.__super__.constructor.apply(this, arguments);
    }

    return Page_Register;

  })(Page);

  Page_Person = (function(_super) {
    var _current_page, _films, _load_counter;

    __extends(Page_Person, _super);

    _films = [];

    _current_page = 0;

    _load_counter = 0;

    function Page_Person(opts) {
      if (opts == null) {
        opts = {};
      }
      this.person_id = opts.person_id;
      Page_Person.__super__.constructor.apply(this, arguments);
      this._e.films_place = $("#films");
      this._e.loadmore = {
        place: $("#load-more-place"),
        btn: $("#btn_loadmore").click((function(_this) {
          return function() {
            return _this.load_more();
          };
        })(this))
      };
      this._app.get_tpl("afilm");
      $(".afilm-place", this._e.films_place).each(function() {
        return _films.push(new Film({
          place: $(this)
        }));
      });
      if (_films.length < 12) {
        this.load_more();
      }
    }

    Page_Person.prototype.load_more = function(page_cnt) {
      var current_counter;
      if (page_cnt == null) {
        page_cnt = 1;
      }
      this._e.loadmore.btn.prop('disabled', true);
      _load_counter++;
      current_counter = _load_counter;
      this._e.loadmore.place.hide();
      return this._app.rest.persons.filmography.read(this.person_id, {}).done((function(_this) {
        return function(data) {
          var item, _i, _len, _ref;
          if (current_counter !== _load_counter) {
            return;
          }
          if (data.items) {
            _ref = data.items;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              item = _ref[_i];
              _films.push(new Film({
                parent: _this._e.films_place,
                vals: item
              }));
            }
          }
          if (Math.ceil(data.total_cnt / data.per_page) > data.page) {
            _this._e.loadmore.place.show();
            _this._e.loadmore.btn.prop('disabled', false);
          }
          return _current_page = data.page;
        };
      })(this)).fail((function(_this) {
        return function(data) {};
      })(this));
    };

    return Page_Person;

  })(Page);

  window.InitApp = function(opts, page_name) {
    if (opts == null) {
      opts = {};
    }
    new App(opts, page_name);
    return delete window.InitApp;
  };

}).call(this);
